---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: quay.io/ansible/creator-ee:v0.18.0@sha256:c89ecbcf47bfa956a2ed3c4939cd29a53298943c8db11eb35d20b9b939ba2a48

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
