---
collections:
  - name: kubernetes.core
    version: 2.3.2
  - name: redhat_cop.controller_configuration
    version: 2.2.5
  - name: ansible.posix
    version: 1.4.0
  - name: community.okd
    version: 2.2.0
  - name: redhat_cop.ah_configuration
    version: 0.9.2
  - name: redhat_cop.ee_utilities
    version: 2.0.4
  - name: redhat_cop.aap_utilities
    version: 2.2.3
