name: Push Image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 1'
  push:
    paths-ignore:
      - 'README.adoc'
    branches:
      - main
jobs:
  publish-lazy-me:
    runs-on: ubuntu-latest
    steps:
    - name: Install  ansible-builder
      run: pip install ansible-builder
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Split repo string for image name
      uses: jungwinter/split@v2
      id: split
      with:
        msg: ${{ github.repository }}
        separator: '/'
    - name: Create EE context
      run: ansible-builder create      
    - name: dirty hack 1 for dirty setup (mixing runner vs. creator ee here and awx collection failing to support python 3.9+)  
      run: sed -i "/.*sanitize.*/a RUN sed -i 's/python38-/python3-/g' /tmp/src/bindep.txt" context/Containerfile
    - name: dirty hack 2 for dirty setup (mixing runner vs. creator ee here and awx collection failing to support python 3.9+)  
      run: sed -i "/.*install-from-bindep.*/i RUN sed -i 's/python38-/python3-/g' /output/bindep/run.txt" context/Containerfile
    - name: Build Image with Buildah
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ steps.split.outputs._1 }}
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./context/Containerfile
        context: context
    - name: Push to quay.io
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/jaeichle
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
